### PR TITLE
NMS 2.0

### PR DESCRIPTION
**Pull request by lukeabsent**

### CODE REVIEW

**Comment by lahma** [comment]
Thank you!

**Comment by lukeabsent** [comment]
Thanks @lahma 
When ,do you think, one can hope for release ?

**Comment by lahma** [comment]
Seems that someone took my repo permissions a notch down so I cannot update variables. Not sure if I have the energy for the process again to get them back, it was a battle. Can you use the MyGet version which should reflect current main?

**Comment by lukeabsent** [comment]
Thanks @lahma, MyGet probably not an option, I'll try waiting, 
Perhaps something has changed on your end ? I see there are some new recent commits to spring-net repo ?

**Comment by lahma** [comment]
@lukeabsent this should now be available on NuGet as version 3.0.1

**Pull request merged**
