### PR TITLE
Sign assemblies with strong name

### PR DESCRIPTION
**Pull request by kales5**
This fixes the issue #212 and now Project that use strong name can use Spring.net
For more see: https://learn.microsoft.com/en-us/dotnet/standard/assembly/strong-named

I had to change one dependency(Experimental.System.Messaging) as it was also not strong named, but luckily there was a package in NuGet that was singed.

### CODE REVIEW

**Comment by lahma** [comment]
I think it should be enough to add this to shared https://github.com/spring-projects/spring-net/blob/main/src/Directory.Build.props ?

**Comment by kales5** [comment]
Yes you are right, I changed that.

**Comment by lahma** [comment]
Thank you!

**Comment by kales5** [comment]
Great, when will this be on NuGet?

**Comment by lahma** [comment]
Impossible to say. I've again lost permissions to configure this repo's settings, but it should already be on MyGet feed.

**Pull request merged**
