### PR TITLE
ReferenceNode throws KeyNotFoundException when CurrentObjectFactory wasn't provided in variables.

### PR DESCRIPTION
**Pull request by kamilpitula**
After a [change](https://github.com/spring-projects/spring-net/commit/05de414adc16956003b81c16e6ac1b75deaa7fe0) that replaced IDictionary with generic IDictionary<string, object> in EvaluationContext class, ReferenceNode throws KeyNotFoundException instead of using default context (non generic dictionaries return null when key does not exsist). I came across this bug when i was trying to resolve Spring expression like this: `expression.GetValue(arg.ExpressionContext, arg.ExpressionVariables)`, where `expression `is of type IExpression. This forced me to add a line like this: `arg.ExpressionVariables[Expression.ReservedVariableNames.RESERVEDPREFIX + "CurrentObjectFactory"] = ContextRegistry.GetContext();` in my code as a workaround.

I have added a check in ReferenceNode that verifies whether key is present in dictionary, and uses default context when it's not (as was initially intended I guess). I have also created some additional unit tests that cover cases I mentioned above.

### CODE REVIEW

**Comment by kamilpitula** [comment]
@lahma 
Hi, it seems that there is a problem with MSBuild in build-windows pipeline. Could you take a look?

**Comment by lahma** [comment]
@kamilpitula I'll have a look probably this evening, seems that build infra needs some updates.

**Comment by kamilpitula** [comment]
> @kamilpitula I'll have a look probably this evening, seems that build infra needs some updates.

Thanks!

**Comment by lahma** [comment]
@kamilpitula if you rebase against main you should have latest build infra which is green against main.

**Comment by lahma** [comment]
Thank you!

**Pull request merged**
