### PR TITLE
Sprint.Testing.Microsoft supports netstandard2.0

### PR DESCRIPTION
**Pull request by TureyLab**

### CODE REVIEW

**Comment by TureyLab** [comment]
Adjusted the project file from Sprint.Testing.Microsoft and Sprint.Testing.Microsoft.Test.

**Comment by lahma** [comment]
Thank you for your contribution!

**Comment by Isdiria** [comment]
> Thank you for your contribution!

It was an honour 😉 When will the next nugets be published?

**Comment by TureyLab** [comment]
> Thank you for your contribution!

It was an honour 😉 When will the next nugets be published?

**Comment by lahma** [comment]
The 3.0.2 release is now live on NuGet and basically is about this netstandard2.0 support update.

**Pull request merged**
